name: Despliegue a Producción

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar para Producción
        run: javac -d out src/main/java/org/example/Main.java

      - name: Ejecutar programa en Producción
        run: java -cp out src/main/java/org/example/Main.java