name: Integración Continua
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar código Java
        run: javac -d out src/main/java/org/example/Main.java

      - name: Ejecutar pruebas
        run: javac src/test/java/MainTest.java
